#
plugin-prefix: "&b[uRPG]"

#
player-defaults:
  level: 1
  experience: 0
  max-health: 100.0

#
rarities:
  common:
    color: "&f"
  uncommon:
    color: "&a"
  rare:
    color: "&9"
  epic:
    color: "&5"
  legendary:
    color: "&6&l"

#
enable-health-action-bar: true

#
stat-identifiers:
  health:
    symbol: ""
    color: "&c"
  defense:
    symbol: ""
    color: "&a"
  strength:
    symbol: ""
    color: "&4"
  dexterity:
    symbol: ""
    color: "&b"
  intelligence:
    symbol: ""
    color: "&d"